[package]
name    = "uinput"
version = "0.1.2"

authors = ["meh. <meh@schizofreni.co>"]
license = "WTFPL"

description = "Linux uinput wrapper."
repository  = "https://github.com/meh/rust-uinput"
keywords    = ["linux", "input"]

[dependencies]
libc       = "0.2"
nix        = "0.5"
uinput-sys = "0.1"
getopts    = "*"
toml       = "0.4.5"
serde_derive = "1.0.11"
serde = "1.0.11"

[dependencies.libudev]
optional = true
version  = "0.2"

[features]
default = ["udev"]
udev    = ["libudev"]
