[package]
name    = "rusty-keys"
version = "0.0.3"

authors = ["moparisthebest <admin@moparisthebest.com>"]
license = "AGPL-3.0"

description = "Linux keyboard mapper"
repository  = "https://code.moparisthebest.com/moparisthebest/rusty-keys"
keywords    = ["linux", "input", "keyboard", "keymapper"]

include = [
    "src/**",
    "Cargo.toml",
    "Cargo.lock",
    "keymap.toml",
    "LICENSE.md",
    "README.md",
]

[dependencies]
libc = "0.2.62"
nix = "0.15.0"
uinput-sys = "0.1.7"
getopts = "0.2.21"
toml = "0.5.3"
serde_derive = "1.0.101"
serde = "1.0.101"
inotify = { version = "0.7.0", default-features = false, features = [] }
