[package]
name    = "rusty-keys"
version = "0.0.2"

authors = ["moparisthebest <admin@moparisthebest.com>"]
license = "AGPL-3.0"

description = "Linux keyboard mapper"
repository  = "https://code.moparisthebest.com/moparisthebest/rusty-keys"
keywords    = ["linux", "input", "keyboard", "keymapper"]

exclude = [
    "keymap.orig.toml",
]

[dependencies]
libc         = "0.2"
nix          = "0.5"
uinput-sys   = "0.1"
getopts      = "0.2.15"
toml         = "0.4.5"
serde_derive = "1.0.11"
serde        = "1.0.11"
inotify      = "0.5.0"

[dependencies.libudev]
optional = true
version  = "0.2"

[features]
default = ["udev"]
udev    = ["libudev"]
